### ISSUE TITLE
Prebuilt Binaries from 5.0.3 causing errors in node:16-alpine docker image, but 5.0.2 same issue now

### ISSUE THREAD

**Issue by Daegalus** [TryGhost/node-sqlite3#1581] opened 2022-04-16 02:50 UTC
I have a node app running in a node:16-alpine docker image, and the application starts fine, but when it tries to load sqlite and use it, I get the following stack trace:

```
node:internal/modules/cjs/loader:1187
  return process.dlopen(module, path.toNamespacedPath(filename));
                 ^
Error: Error relocating /app/node_modules/sqlite3/lib/binding/napi-v6-linux-x64/node_sqlite3.node: fcntl64: symbol not found
    at Object.Module._extensions..node (node:internal/modules/cjs/loader:1187:18)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/app/node_modules/sqlite3/lib/sqlite3-binding.js:4:15)
    at Module._compile (node:internal/modules/cjs/loader:1103:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1157:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12) {
  code: 'ERR_DLOPEN_FAILED'
```

```
# Builder: builds the app, mostly converts TS to JS
FROM node:16-alpine AS ts-builder
WORKDIR /app
COPY . .
RUN rm -rf node_modules
RUN npm install
RUN npm run clean
RUN npm run build

# Cleanup: Remove TS remnants, and only install production deps.
FROM node:16-alpine as ts-remover
WORKDIR /app
RUN mkdir assets
COPY --from=ts-builder /app/package*.json ./
COPY --from=ts-builder /app/build ./
COPY --from=ts-builder /app/assets ./assets
RUN npm install --only=production

# Final image: Only get the JS and Deps. Add SQLITE.
FROM node:16-alpine AS gamemanagerbot
WORKDIR /app
COPY --from=ts-remover /app ./
RUN apk add sqlite
USER 1000
CMD ["client.js"]
```

Currently switching my docker to use the debian node images, incase that works, but thought I would report the alpine problem.

this is happening with version 5.0.2 and 5.0.3 but started happening only when I upgraded to 5.0.2.

**Comment by Daegalus** [comment] 2022-04-16 02:54
So this might be related to the other issues, as under debian, I am getting the glibc issue.

The problem is I am getting it with 5.0.2 and 5.0.3 not just 5.0.3

**Comment by vikaspotluri123** [comment] 2022-04-16 02:57
duplicate of https://github.com/TryGhost/node-sqlite3/issues/1576

**Comment by Daegalus** [comment] 2022-04-16 02:59
@vikaspotluri123 cool, sorry for the duplicate, but would you know why this is happening in 5.0.2 now? I assumed that would work, but the same error is throw on 5.0.2 now.

**Comment by Daegalus** [comment] 2022-04-16 03:02
nvm, i just checked my image. 5.0.3 is being installed regardless of whats in my package.json

**Closed** 2022-04-16 03:02 UTC

**Comment by sbmelvin** [comment] 2022-04-16 21:26
> nvm, i just checked my image. 5.0.3 is being installed regardless of whats in my package.json
Did you hand edit your package.json?

**Comment by Daegalus** [comment] 2022-04-16 22:24
> > nvm, i just checked my image. 5.0.3 is being installed regardless of whats in my package.json
> 
> Did you hand edit your package.json?
> 

Yes the mistake I made was I used `^5.0.2` as the version, which auto upgrades to 5.0.3. when I set it to `5.0.2` it hard pins the version and it worked.
