### ISSUE TITLE
sql in

### ISSUE THREAD

**Issue by LiST-GIT** [TryGhost/node-sqlite3#777] opened 2017-02-18 04:52 UTC
```javascript
// SQL:
// select * from db where id in ( 1, 2, 3 )
// JS:
db.run( 'select * from db where id in ( ? )', [ [ 1, 2, 3 ] ] )
// 'select * from db where id in ( null )'
```

**Comment by daniellockyer** [comment] 2022-04-15 09:37
Closing as dupe of https://github.com/TryGhost/node-sqlite3/issues/762

**Closed by daniellockyer** 2022-04-15 09:37 UTC
