### ISSUE TITLE
can't install on Mac OS Ventura 13.0.1

### ISSUE THREAD

**Issue by bladefang** [TryGhost/node-sqlite3#1670] opened 2023-01-01 16:15 UTC
### Issue Summary

I'm using "nom install sqlite3" to install , but failed.

### Relevant logs or output

Error coming from `npm install`

Command failed with exit code 6: npm install
npm WARN deprecated @npmcli/move-file@1.1.2: This functionality has been moved to @npmcli/fs
npm ERR! code 6
npm ERR! path /private/var/folders/q0/jnhdm_xx5f93h9dn8wgjllsw0000gp/T/be126092d5ec13ff2ca54859f4569cfd/app/web/node_modules/sqlite3
npm ERR! command failed
npm ERR! command sh -c node-pre-gyp install --fallback-to-build
npm ERR! node-pre-gyp info it worked if it ends with ok
npm ERR! node-pre-gyp info using node-pre-gyp@1.0.10
npm ERR! node-pre-gyp info using node@19.3.0 | darwin | x64
npm ERR! node-pre-gyp info check checked for "/private/var/folders/q0/jnhdm_xx5f93h9dn8wgjllsw0000gp/T/be126092d5ec13ff2ca54859f4569cfd/app/web/node_modules/sqlite3/lib/bi
nding/napi-v6-darwin-unknown-x64/node_sqlite3.node" (not found)
npm ERR! node-pre-gyp http GET https://github.com/TryGhost/node-sqlite3/releases/download/v5.1.4/napi-v6-darwin-unknown-x64.tar.gz
npm ERR! node-pre-gyp info install unpacking napi-v6-darwin-unknown-x64/node_sqlite3.node
npm ERR! node-pre-gyp ERR! Completion callback never invoked!
npm ERR! node-pre-gyp ERR! System Darwin 22.1.0
npm ERR! node-pre-gyp ERR! command "/usr/local/Cellar/node/19.3.0/bin/node"
"/private/var/folders/q0/jnhdm_xx5f93h9dn8wgjllsw0000gp/T/be126092d5ec13ff2ca54859f4569cfd/app/web/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
npm ERR! node-pre-gyp ERR! cwd /private/var/folders/q0/jnhdm_xx5f93h9dn8wgjllsw0000gp/T/be126092d5ec13ff2ca54859f4569cfd/app/web/node_modules/sqlite3
npm ERR! node-pre-gyp ERR! node -v v19.3.0
npm ERR! node-pre-gyp ERR! node-pre-gyp -v v1.0.10

### Version

latest

### Node.js Version

v19.3.0

### How did you install the library?

Mac OS Ventura 13.0.1

**Comment by daniellockyer** [comment] 2023-01-04 11:07
This is a duplicate of https://github.com/TryGhost/node-sqlite3/issues/1662

**Closed by daniellockyer** 2023-01-04 11:07 UTC
Labels: install problem
