### ISSUE TITLE
Can't make debugging work

### ISSUE THREAD

**Issue by jorfermo** [TryGhost/node-sqlite3#680] opened 2016-07-21 17:21 UTC
I'm trying to use the [debugging](https://github.com/mapbox/node-sqlite3/wiki/Debugging) options but I failed to understand how to do it.

```
var sqlite3 = require('sqlite3');
sqlite3.verbose();
var db = new sqlite3.Database(":memory:");
db.run("CREATE TABLE tb1 (ID int)");
db.run("UPDATE tb1 SET ID = ?", [3, 6], function(error){
  if (error){
      throw(new Error(error));
  }
});
```

This shows this error:

```
node_modules/sqlite3/lib/trace.js:28 Uncaught Error: Error: SQLITE_RANGE: bind or column index out of range(anonymous function) @ VM470:3replacement @ 
node_modules/sqlite3/lib/trace.js:20replacement @ 
node_modules/sqlite3/lib/trace.js:20
```

In the wiki, says: "_When you throw an error from a callback passed to any of the database functions, node-sqlite3 will append the stack trace information from the original call, like this:_"

What am I missing?

**Comment by webtop** [comment] 2016-08-21 19:43
I'm having a similar issue. I have the the database in verbose mode, and have set up listeners on 'trace' and 'profile', but I get no result when executing a 'bad' query.

`if (con.MODE == 'dev') {
    sqlite3.verbose();

    db.on('trace', function (sql) {
        common.log(sql);
    });

    db.on('profile', function (sql, ms) {
        common.log(sql);
        common.log(ms);
    });
}`

When executing any query, good or bad, I get no response from the 'on' events.
My common.log method simply adds datestamp and format extras.

Module version: 3.1.4
Node version: 4.4.5

Thanks
Paul

**Comment by webtop** [comment] 2016-08-22 04:17
I just debugged the issue and if the SQL statement is bad, I guess it is never actually "executed", and thus trace never gets triggered.
Using util.inspect() helps in the callback, as does causing another node error like function not found. That causes the exception object to be passed to the callback which can then be examined.

**Comment by jorfermo** [comment] 2016-08-22 09:40
Can You post a working example?

**Comment by michael-ts** [comment] 2017-08-13 16:59
I'm seeing some strange behavior from trace/profile as well.  It seems like the trace event sometimes isn't call right away.  As a result, I can see my code receive the callback from a get() call, then issue a close to the database, and *then* I see the trace and profile events from the SELECT that was already closed.  This is kinda a big deal for me, as I'm trying to debug an issue that occurs when there are several pending requests - I exit the process on an error, and it *appears* that I am getting an error on a statement that was never executed yet I already got the callback for.

**Comment by jaredkrinke** [comment] 2019-11-19 18:04
I noticed that I receive the "SQLITE_RANGE: column index out of range" error if I supply more parameters than are actually referenced by my query. Given that jorfermo's original code has *one* "?" parameter in the query, but there are *two* values in the parameter array, that is likely the cause of the error. Side note: I think his code assumes the queries are serialized.

**Comment by daniellockyer** [comment] 2022-09-17 18:04
I can't seem to reproduce this nor do I see a bug listed here that is outside of what is expected. Closing for now 🙂

**Closed by daniellockyer** 2022-09-17 18:04 UTC
