### ISSUE TITLE
I'm getting complile failure error(node-pre-gyp/lib/util/compile.js)

### ISSUE THREAD

**Issue by RobertRajcool** [TryGhost/node-sqlite3#908] opened 2017-11-15 13:55 UTC
WARNING in ./~/node-gyp/lib/Find-VS2017.cs
Module parse failed: /home/robert/electron/angular2-electron/node_modules/node-gyp/lib/Find-VS2017.cs Unexpected token (7:6)
You may need an appropriate loader to handle this file type.
| // Usage:
| // powershell -ExecutionPolicy Unrestricted -Version "2.0" -Command "&{Add-Type -Path Find-VS2017.cs; [VisualStudioConfiguration.Main]::Query()}"
| using System;
| using System.Text;
| using System.Runtime.InteropServices;
 @ ./~/node-gyp/lib ^\.\/.*$
 @ ./~/node-gyp/lib/node-gyp.js
 @ ./~/node-pre-gyp/lib/util/compile.js
 @ ./~/node-pre-gyp/lib ^\.\/.*$
 @ ./~/node-pre-gyp/lib/node-pre-gyp.js
 @ ./~/sqlite3/lib/sqlite3.js
 @ ./src/app/login/login.component.ts
 @ ./src/app/app.module.ts
 @ ./src/main.ts
 @ multi webpack-dev-server/client?http://localhost:4200/ ./src/main.ts

WARNING in ./~/node-pre-gyp/lib/util/compile.js
Module not found: Error: Can't resolve 'npm' in '/home/robert/electron/angular2-electron/node_modules/node-pre-gyp/lib/util'
 @ ./~/node-pre-gyp/lib/util/compile.js 39:27-49
 @ ./~/node-pre-gyp/lib ^\.\/.*$
 @ ./~/node-pre-gyp/lib/node-pre-gyp.js
 @ ./~/sqlite3/lib/sqlite3.js
 @ ./src/app/login/login.component.ts
 @ ./src/app/app.module.ts
 @ ./src/main.ts
 @ multi webpack-dev-server/client?http://localhost:4200/ ./src/main.ts

WARNING in ./~/sqlite3/lib/sqlite3.js
4:14-35 Critical dependency: the request of a dependency is an expression

WARNING in ./~/node-pre-gyp/lib/pre-binding.js
19:22-48 Critical dependency: the request of a dependency is an expression

WARNING in ./~/node-pre-gyp/lib/util/versioning.js
16:20-67 Critical dependency: the request of a dependency is an expression

ERROR in ./~/node-gyp/lib/node-gyp.js
Module not found: Error: Can't resolve '../package' in '/home/robert/electron/angular2-electron/node_modules/node-gyp/lib'
 @ ./~/node-gyp/lib/node-gyp.js 67:16-37
 @ ./~/node-pre-gyp/lib/util/compile.js
 @ ./~/node-pre-gyp/lib ^\.\/.*$
 @ ./~/node-pre-gyp/lib/node-pre-gyp.js
 @ ./~/sqlite3/lib/sqlite3.js
 @ ./src/app/login/login.component.ts
 @ ./src/app/app.module.ts
 @ ./src/main.ts
 @ multi webpack-dev-server/client?http://localhost:4200/ ./src/main.ts

ERROR in ./~/osenv/osenv.js
Module not found: Error: Can't resolve 'child_process' in '/home/robert/electron/angular2-electron/node_modules/osenv'
 @ ./~/osenv/osenv.js 3:11-35
 @ ./~/nopt/lib/nopt.js
 @ ./~/node-pre-gyp/lib/node-pre-gyp.js
 @ ./~/sqlite3/lib/sqlite3.js
 @ ./src/app/login/login.component.ts
 @ ./src/app/app.module.ts
 @ ./src/main.ts
 @ multi webpack-dev-server/client?http://localhost:4200/ ./src/main.ts

ERROR in ./~/node-pre-gyp/lib/info.js
Module not found: Error: Can't resolve 'aws-sdk' in '/home/robert/electron/angular2-electron/node_modules/node-pre-gyp/lib'
 @ ./~/node-pre-gyp/lib/info.js 14:14-32
 @ ./~/node-pre-gyp/lib ^\.\/.*$
 @ ./~/node-pre-gyp/lib/node-pre-gyp.js
 @ ./~/sqlite3/lib/sqlite3.js
 @ ./src/app/login/login.component.ts
 @ ./src/app/app.module.ts
 @ ./src/main.ts
 @ multi webpack-dev-server/client?http://localhost:4200/ ./src/main.ts

ERROR in ./~/uid-number/uid-number.js
Module not found: Error: Can't resolve 'child_process' in '/home/robert/electron/angular2-electron/node_modules/uid-number'
 @ ./~/uid-number/uid-number.js 9:20-44
 @ ./~/tar-pack/index.js
 @ ./~/node-pre-gyp/lib/package.js
 @ ./~/node-pre-gyp/lib ^\.\/.*$
 @ ./~/node-pre-gyp/lib/node-pre-gyp.js
 @ ./~/sqlite3/lib/sqlite3.js
 @ ./src/app/login/login.component.ts
 @ ./src/app/app.module.ts
 @ ./src/main.ts
 @ multi webpack-dev-server/client?http://localhost:4200/ ./src/main.ts

ERROR in ./~/node-pre-gyp/lib/publish.js
Module not found: Error: Can't resolve 'aws-sdk' in '/home/robert/electron/angular2-electron/node_modules/node-pre-gyp/lib'
 @ ./~/node-pre-gyp/lib/publish.js 17:14-32
 @ ./~/node-pre-gyp/lib ^\.\/.*$
 @ ./~/node-pre-gyp/lib/node-pre-gyp.js
 @ ./~/sqlite3/lib/sqlite3.js
 @ ./src/app/login/login.component.ts
 @ ./src/app/app.module.ts
 @ ./src/main.ts
 @ multi webpack-dev-server/client?http://localhost:4200/ ./src/main.ts

ERROR in ./~/node-pre-gyp/lib/testbinary.js
Module not found: Error: Can't resolve 'child_process' in '/home/robert/electron/angular2-electron/node_modules/node-pre-gyp/lib'
 @ ./~/node-pre-gyp/lib/testbinary.js 10:9-33
 @ ./~/node-pre-gyp/lib ^\.\/.*$
 @ ./~/node-pre-gyp/lib/node-pre-gyp.js
 @ ./~/sqlite3/lib/sqlite3.js
 @ ./src/app/login/login.component.ts
 @ ./src/app/app.module.ts
 @ ./src/main.ts
 @ multi webpack-dev-server/client?http://localhost:4200/ ./src/main.ts

ERROR in ./~/node-pre-gyp/lib/unpublish.js
Module not found: Error: Can't resolve 'aws-sdk' in '/home/robert/electron/angular2-electron/node_modules/node-pre-gyp/lib'
 @ ./~/node-pre-gyp/lib/unpublish.js 15:14-32
 @ ./~/node-pre-gyp/lib ^\.\/.*$
 @ ./~/node-pre-gyp/lib/node-pre-gyp.js
 @ ./~/sqlite3/lib/sqlite3.js
 @ ./src/app/login/login.component.ts
 @ ./src/app/app.module.ts
 @ ./src/main.ts
 @ multi webpack-dev-server/client?http://localhost:4200/ ./src/main.ts

ERROR in ./~/detect-libc/lib/detect-libc.js
Module not found: Error: Can't resolve 'child_process' in '/home/robert/electron/angular2-electron/node_modules/detect-libc/lib'
 @ ./~/detect-libc/lib/detect-libc.js 4:16-40
 @ ./~/node-pre-gyp/lib/util/versioning.js
 @ ./~/node-pre-gyp/lib ^\.\/.*$
 @ ./~/node-pre-gyp/lib/node-pre-gyp.js
 @ ./~/sqlite3/lib/sqlite3.js
 @ ./src/app/login/login.component.ts
 @ ./src/app/app.module.ts
 @ ./src/main.ts
 @ multi webpack-dev-server/client?http://localhost:4200/ ./src/main.ts

ERROR in ./~/node-gyp/lib/node-gyp.js
Module not found: Error: Can't resolve 'child_process' in '/home/robert/electron/angular2-electron/node_modules/node-gyp/lib'
 @ ./~/node-gyp/lib/node-gyp.js 16:20-44
 @ ./~/node-pre-gyp/lib/util/compile.js
 @ ./~/node-pre-gyp/lib ^\.\/.*$
 @ ./~/node-pre-gyp/lib/node-pre-gyp.js
 @ ./~/sqlite3/lib/sqlite3.js
 @ ./src/app/login/login.component.ts
 @ ./src/app/app.module.ts
 @ ./src/main.ts
 @ multi webpack-dev-server/client?http://localhost:4200/ ./src/main.ts

ERROR in ./~/node-pre-gyp/lib/util/compile.js
Module not found: Error: Can't resolve 'child_process' in '/home/robert/electron/angular2-electron/node_modules/node-pre-gyp/lib/util'
 @ ./~/node-pre-gyp/lib/util/compile.js 9:9-33
 @ ./~/node-pre-gyp/lib ^\.\/.*$
 @ ./~/node-pre-gyp/lib/node-pre-gyp.js
 @ ./~/sqlite3/lib/sqlite3.js
 @ ./src/app/login/login.component.ts
 @ ./src/app/app.module.ts
 @ ./src/main.ts
 @ multi webpack-dev-server/client?http://localhost:4200/ ./src/main.ts

ERROR in ./~/node-gyp/lib/build.js
Module not found: Error: Can't resolve 'child_process' in '/home/robert/electron/angular2-electron/node_modules/node-gyp/lib'
 @ ./~/node-gyp/lib/build.js 14:11-35
 @ ./~/node-gyp/lib ^\.\/.*$
 @ ./~/node-gyp/lib/node-gyp.js
 @ ./~/node-pre-gyp/lib/util/compile.js
 @ ./~/node-pre-gyp/lib ^\.\/.*$
 @ ./~/node-pre-gyp/lib/node-pre-gyp.js
 @ ./~/sqlite3/lib/sqlite3.js
 @ ./src/app/login/login.component.ts
 @ ./src/app/app.module.ts
 @ ./src/main.ts
 @ multi webpack-dev-server/client?http://localhost:4200/ ./src/main.ts

ERROR in ./~/node-gyp/lib/configure.js
Module not found: Error: Can't resolve 'child_process' in '/home/robert/electron/angular2-electron/node_modules/node-gyp/lib'
 @ ./~/node-gyp/lib/configure.js 19:9-33
 @ ./~/node-gyp/lib ^\.\/.*$
 @ ./~/node-gyp/lib/node-gyp.js
 @ ./~/node-pre-gyp/lib/util/compile.js
 @ ./~/node-pre-gyp/lib ^\.\/.*$
 @ ./~/node-pre-gyp/lib/node-pre-gyp.js
 @ ./~/sqlite3/lib/sqlite3.js
 @ ./src/app/login/login.component.ts
 @ ./src/app/app.module.ts
 @ ./src/main.ts
 @ multi webpack-dev-server/client?http://localhost:4200/ ./src/main.ts

ERROR in ./~/node-gyp/lib/find-vs2017.js
Module not found: Error: Can't resolve 'child_process' in '/home/robert/electron/angular2-electron/node_modules/node-gyp/lib'
 @ ./~/node-gyp/lib/find-vs2017.js 2:15-39
 @ ./~/node-gyp/lib ^\.\/.*$
 @ ./~/node-gyp/lib/node-gyp.js
 @ ./~/node-pre-gyp/lib/util/compile.js
 @ ./~/node-pre-gyp/lib ^\.\/.*$
 @ ./~/node-pre-gyp/lib/node-pre-gyp.js
 @ ./~/sqlite3/lib/sqlite3.js
 @ ./src/app/login/login.component.ts
 @ ./src/app/app.module.ts
 @ ./src/main.ts
 @ multi webpack-dev-server/client?http://localhost:4200/ ./src/main.ts
webpack: Failed to compile.

**Comment by wmertens** [comment] 2017-12-26 20:43
duplicate of #909 - please don't pollute open source projects; please close this.

**Closed** 2022-04-15 09:28 UTC
