### ISSUE TITLE
No support for extremely long strings or blobs

### ISSUE THREAD

**Issue by ezsoftware** [TryGhost/node-sqlite3#668] opened 2016-06-23 17:02 UTC
sqlite3_bind_text only binds up to 32,767 characters, for strings longer than that it needs to use sqlite3_bind_text64.

This behavior causes all strings longer than 32,767 to be truncated when being inserted through a binding.

**Comment by tmcw** [comment] 2016-10-05 15:30
Closing in favor of #424, which discusses the implementation of the API for large data. Happy to accept a PR implementing that suggestion.

**Comment by rnewman** [comment] 2016-10-05 16:04
Is #424 really a substitute for this?

How is a caller to know that large strings can't be stored via `node-sqlite3`, and must instead be stored as blobs through a separate API?

A cursory read of the API suggests that fixing this should be relatively straightforward, either switching on the length of the input string and using the `_64` variant with a 64-bit explicit length, or always using the `_64` variant.

Would you accept a pull request for this issue?

**Comment by tmcw** [comment] 2016-10-05 16:07
Yep, would definitely accept a PR that implements a fix and includes unit tests!

**Comment by rnewman** [comment] 2016-10-05 16:27
Can I suggest then that you reopen this and drop the "or blobs" from the title? If it affects Datomish (https://github.com/mozilla/datomish/issues/65) I'll try to find time to fix it.

**Comment by tmcw** [comment] 2016-10-05 16:55
Sure, reopened.

**Comment by rnewman** [comment] 2016-10-06 22:49
I am not able to reproduce this issue with 3.1.4 (which seems to include sqlite 3.9.1) on Node 6.2.0.

I can push 660,004-character strings through the interface all day long without issue. The following test code (using ClojureScript and our own promise wrapper) passes:

```
  ;; Make a string that's nicely over the 32K limit in node-sqlite3/#668.
  (let [s (str "be" (apply str (repeat 330000 "la")) "st")]
…
          (<? (s/execute! db ["CREATE TABLE strs (x INTEGER, a TEXT)"]))
          (<? (s/execute! db ["INSERT INTO strs VALUES (42, ?)" s]))

          ;; Test retrieval via binding comparison.
          (is (= (<? (s/all-rows db ["SELECT x FROM strs WHERE a = ?" s]))
                 [{:x 42}]))
          
          ;; Test computation.
          (is (= (<? (s/all-rows db ["SELECT length(a) AS yvr FROM strs"]))
                 [{:yvr 660004}]))
          (is (= (<? (s/all-rows db ["SELECT length(?) AS yvr FROM strs" s]))
                 [{:yvr 660004}]))

          ;; Test round-tripping.
          (is (= (<? (s/all-rows db ["SELECT x, a FROM strs"]))
                 [{:x 42, :a s}]))
          (is (= (<? (s/all-rows db ["SELECT ? AS yyz FROM strs" s]))
                 [{:yyz s}]))
```

Did someone accidentally fix this, or is this platform-specific?

**Comment by rnewman** [comment] 2016-10-06 22:56
Indeed, I've tested with a string 66,000,004 characters long with no issues.

I'm on a modern 64-bit Mac.

**Comment by kroggen** [comment] 2016-10-07 17:55
I did not find any comment about a limit on the string size in the [documentation](https://www.sqlite.org/c3ref/bind_blob.html).

There is no much difference between `sqlite3_bind_text` and `sqlite3_bind_text64` in the [source](http://www.sqlite.org/cgi/src/artifact/8272f9342c39ab8d7eb4b9decc6caa7bc75b7d83?txt=1&ln=1364) too.

Both call the same [bindText](http://www.sqlite.org/cgi/src/artifact/8272f9342c39ab8d7eb4b9decc6caa7bc75b7d83?txt=1&ln=1272) function.

**Closed** 2022-05-03 12:32 UTC
