### ISSUE TITLE
sqlite3 error when trying to connect to database

### ISSUE THREAD

**Issue by sireeshdevaraj** [TryGhost/node-sqlite3#1542] opened 2022-02-07 12:38 UTC
let db = new sqlite3.Database('shiro', (err) => {
         ^

TypeError: sqlite3.Database is not a constructor
    at Object.<anonymous> (D:\desktop\nsql\index.js:12:10)
    at Module._compile (node:internal/modules/cjs/loader:1097:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1149:10)
    at Module.load (node:internal/modules/cjs/loader:975:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:17:47

**Comment by daniellockyer** [comment] 2022-04-17 06:38
Would you be able to provide more of a reproduction case? 🙂

**Comment by daniellockyer** [comment] 2022-04-17 06:39
Actually, I suspect this is a duplicate of https://github.com/TryGhost/node-sqlite3/issues/1532

**Closed by daniellockyer** 2022-04-17 06:38 UTC

**Comment by sireeshdevaraj** [comment] 2022-04-19 07:16
```javascript
const sqlite3=require('sqlite3').verbose;

let db = new sqlite3.Database('shiro', (err) => {
  if (err) {
    return console.error(err.message);
  }
  console.log('Connected to the in-memory SQlite database.');
});

```
Just basic intro.
