### ISSUE TITLE
Version with promisses

### ISSUE THREAD

**Issue by SrStick** [TryGhost/node-sqlite3#1636] opened 2022-09-14 04:49 UTC
### Summary

I think it would be interesting if there was a version of the database.run(), get() and all() methods that uses Promise instead of callback.
I can send a pull request with these changes, what do you think?

### Proposed implementation

the database.run(), get(), and all() methods should be implemented using Promisses

**Comment by daniellockyer** [comment] 2022-09-14 06:45
Hey @SrStick 👋🏻 I would love to see a PR for this 🙂

**Comment by RinkAttendant6** [comment] 2022-11-13 06:28
This appears to be a duplicate of https://github.com/TryGhost/node-sqlite3/issues/834

**Comment by daniellockyer** [comment] 2022-11-14 08:33
Good point - closing as a duplicate of https://github.com/TryGhost/node-sqlite3/issues/834

**Closed by daniellockyer** 2022-11-14 08:33 UTC
Labels: feature request
