### ISSUE TITLE
How to tell if a transaction is active?

### ISSUE THREAD

**Issue by TenaciousDEK** [TryGhost/node-sqlite3#714] opened 2016-09-22 16:00 UTC
I need to be able to tell if a transaction is active (e.g. via BEGIN TRANSACTION) or not. Is there any facility for this in node-sqlite3?

For example, in the Sqlite.org C interface you can call this:-
`int sqlite3_get_autocommit(sqlite3*);`

(See [Sqlite Docs - Test For Auto-Commit Mode](http://www.sqlite.org/c3ref/get_autocommit.html) )

I could try to keep track of this myself, but apparently some errors can roll back transactions automatically so it's difficult to track this reliably. The only way is via the sqlite3_get_autocommit() call apparently.

Thanks!

**Comment by YugoAmaryl** [comment] 2017-01-06 09:01
Have you explored using a mutex?

https://www.npmjs.com/package/node-mutex

I'm facing the same issue, writing a server using publish/subscribe service.
The server can receive a message, start a transaction, then receive a second message requiring a new transaction while the first one is still executing.

**Comment by fictorial** [comment] 2017-02-11 04:06
Can't you just use a queue for all your DML?  

Enqueue work functions that are invoked after a BEGIN. Have the work function callback(error).  If error, ROLLBACK else COMMIT. Either way, pop the next work function off the queue and repeat.

Something like this?

````node.js
var isPromise = require('is-promise')

var queue = []
var db

function enqueueDML (work) {
  queue.push(work)
  if (queue.length === 1) next()
}

function next () {
  if (queue.length === 0) return

  var work
  while (typeof work !== 'function' && queue.length > 0) {
    work = queue.shift()
  }

  if (typeof work !== 'function') return

  db.serialize(function () {
    db.exec('BEGIN')

    try {
      const promise = work.call(db, function (error) {
        if (error) db.exec('ROLLBACK')
        else db.exec('COMMIT')
        next()
      })

      if (isPromise(promise)) {
        promise.then(function () {
          db.exec('COMMIT')
          next()
        }).catch(function () {
          db.exec('ROLLBACK')
          next()
        })
      }
    } catch (error) {
      db.exec('ROLLBACK')
      next()
    }
  })
}

module.exports = function (connection) {
  db = connection
  return enqueueDML
}
````

**Comment by fictorial** [comment] 2017-02-12 18:46
I put this in a simple package with promises support as well.  Hopefully it's useful for someone.  Open issues there if there's something I missed.  Thanks!  https://github.com/fictorial/sqlite3-utils

**Comment by jordandc1** [comment] 2019-12-04 17:12
I got the same issue here. If you commit a large amount of data, the commit statement will execute without any issue, but the database is still locked. When you start a new transaction, you will get an error, so the problem is how to know when the database is unlocked and ready to write data.
Right now, I just wait for the commit like 30 secs for 10000 inserts. I am wondering if you guys have some optimal solution to improve the performance.

**Comment by daniellockyer** [comment] 2022-05-21 11:25
Closing as duplicate of https://github.com/TryGhost/node-sqlite3/issues/304

**Closed by daniellockyer** 2022-05-21 11:25 UTC
Labels: question
